[ids]
*

[main]
# Maps Caps Lock to Escape natively
capslock = escape

# Override left alt when pressed to signal menu key
leftalt = overload(alt, rightalt)

# Sets up a modifier layer (like Mode_switch) on the Alt key
leftalt = layer(nav)

[main]
leftalt = overload(nav, rightalt)

# The :A tells keyd to apply the Alt modifier to any unmapped keys
[nav:A]
# Replicates hjkl xmodmap bindings
h = left
j = down
k = up
l = right

