# Managed by chezmoi. Edit home/dot_config/gtk-4.0/settings.ini in the dotfiles repo.
[Settings]
gtk-theme-name=Yaru-olive-dark
gtk-icon-theme-name=Yaru-olive-dark
gtk-font-name=Sans 10
gtk-cursor-theme-name=Adwaita
gtk-cursor-theme-size=24
