-- Hipster Green — matches kitty current-theme.conf

vim.cmd.highlight 'clear'
if vim.fn.exists 'syntax_on' then
  vim.cmd.syntax 'reset'
end
vim.o.termguicolors = true
vim.g.colors_name = 'hipster-green'

local colors = {
  bg = '#0f0a05',
  bg_alt = '#0c0804',
  fg = '#84c137',
  fg_bright = '#eeeeee',
  cursor = '#23ff18',
  selection = '#083905',
  black = '#000000',
  grey = '#666666',
  grey_light = '#bfbfbf',
  white = '#e5e5e5',
  red = '#b6204a',
  bright_red = '#e50000',
  green = '#00a600',
  bright_green = '#86a83e',
  yellow = '#bebe00',
  bright_yellow = '#e5e500',
  blue = '#246db2',
  bright_blue = '#0000ff',
  magenta = '#b200b2',
  bright_magenta = '#e500e5',
  cyan = '#00a6b2',
  bright_cyan = '#00e5e5',
  comment = '#666666',
  nontext = '#0c0804',
  visual = '#083905',
  transparent_bg = '#0c0804',
  transparent_green = '#0f1a0a',
  transparent_red = '#1a0a10',
  transparent_blue = '#0a1018',
  transparent_yellow = '#141408',
}

vim.g.terminal_color_0 = colors.black
vim.g.terminal_color_1 = colors.red
vim.g.terminal_color_2 = colors.green
vim.g.terminal_color_3 = colors.yellow
vim.g.terminal_color_4 = colors.blue
vim.g.terminal_color_5 = colors.magenta
vim.g.terminal_color_6 = colors.cyan
vim.g.terminal_color_7 = colors.grey_light
vim.g.terminal_color_8 = colors.grey
vim.g.terminal_color_9 = colors.bright_red
vim.g.terminal_color_10 = colors.bright_green
vim.g.terminal_color_11 = colors.bright_yellow
vim.g.terminal_color_12 = colors.bright_blue
vim.g.terminal_color_13 = colors.bright_magenta
vim.g.terminal_color_14 = colors.bright_cyan
vim.g.terminal_color_15 = colors.white
vim.g.terminal_color_background = colors.bg
vim.g.terminal_color_foreground = colors.fg

local groups = vim.tbl_extend('force', {
  Normal = { fg = colors.fg, bg = colors.bg },
  NormalNC = { fg = colors.bright_green, bg = colors.bg },
  Comment = { fg = colors.comment, italic = true },
  Constant = { fg = colors.bright_yellow },
  String = { fg = colors.bright_green },
  Character = { fg = colors.bright_cyan },
  Number = { fg = colors.bright_yellow },
  Boolean = { fg = colors.cyan },
  Float = { fg = colors.bright_yellow },
  Identifier = { fg = colors.fg },
  Function = { fg = colors.cyan },
  Statement = { fg = colors.green },
  Conditional = { fg = colors.green },
  Repeat = { fg = colors.green },
  Label = { fg = colors.bright_magenta },
  Operator = { fg = colors.fg },
  Keyword = { fg = colors.green },
  Exception = { fg = colors.red },
  PreProc = { fg = colors.magenta },
  Type = { fg = colors.blue },
  StorageClass = { fg = colors.green },
  Structure = { fg = colors.blue },
  Typedef = { fg = colors.blue },
  Special = { fg = colors.cyan },
  SpecialChar = { fg = colors.bright_cyan },
  Tag = { fg = colors.green },
  Delimiter = { fg = colors.fg },
  SpecialComment = { fg = colors.comment, bold = true },
  Underlined = { underline = true, fg = colors.cyan },
  Ignore = { fg = colors.grey },
  Error = { fg = colors.bright_red, bold = true },
  Todo = { fg = colors.bg, bg = colors.yellow, bold = true },
  Cursor = { fg = colors.bg, bg = colors.cursor },
  lCursor = { link = 'Cursor' },
  CursorLine = { bg = colors.selection },
  CursorLineNr = { fg = colors.cursor, bold = true },
  CursorColumn = { bg = colors.transparent_bg },
  ColorColumn = { bg = colors.transparent_bg },
  LineNr = { fg = colors.grey },
  LineNrAbove = { fg = colors.grey },
  LineNrBelow = { fg = colors.grey },
  SignColumn = { fg = colors.grey, bg = colors.bg },
  Folded = { fg = colors.bright_green, bg = colors.bg_alt },
  FoldColumn = { fg = colors.grey, bg = colors.bg },
  Visual = { bg = colors.visual },
  Search = { fg = colors.bg, bg = colors.bright_green },
  IncSearch = { fg = colors.bg, bg = colors.cursor },
  Substitute = { fg = colors.bg, bg = colors.bright_magenta, bold = true },
  MatchParen = { bold = true, fg = colors.cursor, bg = colors.selection },
  ModeMsg = { fg = colors.fg_bright },
  MsgArea = { fg = colors.fg },
  MoreMsg = { fg = colors.bright_green },
  Question = { fg = colors.cyan },
  WarningMsg = { fg = colors.yellow },
  ErrorMsg = { fg = colors.bright_red },
  WinSeparator = { fg = colors.selection, bg = colors.bg },
  StatusLine = { fg = colors.fg_bright, bg = colors.transparent_bg },
  StatusLineNC = { fg = colors.grey, bg = colors.transparent_bg },
  StatusLineTerm = { link = 'StatusLine' },
  StatusLineTermNC = { link = 'StatusLineNC' },
  WinBar = { fg = colors.fg, bg = colors.transparent_bg, bold = true },
  WinBarNC = { fg = colors.grey, bg = colors.transparent_bg },
  TabLine = { fg = colors.grey, bg = colors.bg_alt },
  TabLineFill = { bg = colors.bg_alt },
  TabLineSel = { fg = colors.fg_bright, bg = colors.selection, bold = true },
  Pmenu = { fg = colors.fg_bright, bg = colors.transparent_blue },
  PmenuSel = { fg = colors.bg, bg = colors.bright_green },
  PmenuSbar = { bg = colors.transparent_blue },
  PmenuThumb = { bg = colors.selection },
  WildMenu = { fg = colors.bg, bg = colors.bright_green },
  DiffAdd = { fg = colors.bright_green, bg = colors.transparent_green },
  DiffChange = { fg = colors.yellow, bg = colors.transparent_yellow },
  DiffDelete = { fg = colors.bright_red, bg = colors.transparent_red },
  DiffText = { fg = colors.fg_bright, bg = colors.selection },
  DiagnosticError = { fg = colors.bright_red },
  DiagnosticWarn = { fg = colors.yellow },
  DiagnosticInfo = { fg = colors.cyan },
  DiagnosticHint = { fg = colors.bright_green },
  DiagnosticVirtualTextError = { fg = colors.bright_red, bg = colors.transparent_red },
  DiagnosticVirtualTextWarn = { fg = colors.yellow, bg = colors.transparent_yellow },
  DiagnosticVirtualTextInfo = { fg = colors.cyan, bg = colors.transparent_blue },
  DiagnosticVirtualTextHint = { fg = colors.bright_green, bg = colors.transparent_green },
  DiagnosticUnderlineError = { undercurl = true, sp = colors.bright_red },
  DiagnosticUnderlineWarn = { undercurl = true, sp = colors.yellow },
  DiagnosticUnderlineInfo = { undercurl = true, sp = colors.cyan },
  DiagnosticUnderlineHint = { undercurl = true, sp = colors.bright_green },
  GitSignsAdd = { fg = colors.bright_green },
  GitSignsChange = { fg = colors.cyan },
  GitSignsDelete = { fg = colors.bright_red },
  TelescopeBorder = { fg = colors.selection },
  TelescopePromptBorder = { fg = colors.green },
  TelescopeResultsBorder = { fg = colors.selection },
  TelescopePreviewBorder = { fg = colors.selection },
  TelescopeTitle = { fg = colors.fg_bright, bold = true },
  TelescopePromptTitle = { fg = colors.cursor, bold = true },
  TelescopeResultsTitle = { fg = colors.bright_green, bold = true },
  TelescopePreviewTitle = { fg = colors.cyan, bold = true },
  NvimTreeNormal = { fg = colors.fg, bg = colors.bg },
  NvimTreeRootFolder = { fg = colors.fg_bright, bold = true },
  NvimTreeFolderName = { fg = colors.bright_green },
  NvimTreeFolderIcon = { fg = colors.green },
  NvimTreeEmptyFolderName = { fg = colors.grey },
  NvimTreeIndentMarker = { fg = colors.selection },
  BufferLineFill = { bg = colors.bg_alt },
  BufferLineBackground = { fg = colors.grey, bg = colors.bg_alt },
  BufferLineBufferSelected = { fg = colors.fg_bright, bg = colors.selection },
  BufferLineIndicatorSelected = { fg = colors.cursor },
  BufferLineSeparator = { fg = colors.bg_alt, bg = colors.bg_alt },
  BufferLineSeparatorSelected = { fg = colors.selection, bg = colors.selection },
  LspInlayHint = { fg = colors.blue, italic = true },
}, {
  ['@comment'] = { fg = colors.comment, italic = true },
  ['@constant'] = { fg = colors.bright_yellow },
  ['@string'] = { fg = colors.bright_green },
  ['@character'] = { fg = colors.bright_cyan },
  ['@number'] = { fg = colors.bright_yellow },
  ['@boolean'] = { fg = colors.cyan },
  ['@float'] = { fg = colors.bright_yellow },
  ['@function'] = { fg = colors.cyan },
  ['@function.builtin'] = { fg = colors.cyan },
  ['@function.macro'] = { fg = colors.magenta },
  ['@parameter'] = { fg = colors.fg },
  ['@keyword'] = { fg = colors.green },
  ['@keyword.operator'] = { fg = colors.fg },
  ['@keyword.return'] = { fg = colors.green },
  ['@conditional'] = { fg = colors.green },
  ['@repeat'] = { fg = colors.green },
  ['@label'] = { fg = colors.bright_magenta },
  ['@operator'] = { fg = colors.fg },
  ['@exception'] = { fg = colors.red },
  ['@type'] = { fg = colors.blue },
  ['@type.builtin'] = { fg = colors.blue },
  ['@storageclass'] = { fg = colors.green },
  ['@structure'] = { fg = colors.blue },
  ['@namespace'] = { fg = colors.bright_green },
  ['@include'] = { fg = colors.magenta },
  ['@tag'] = { fg = colors.green },
  ['@tag.attribute'] = { fg = colors.bright_green },
  ['@tag.delimiter'] = { fg = colors.grey },
  ['@property'] = { fg = colors.bright_green },
  ['@variable'] = { fg = colors.fg },
  ['@variable.member'] = { fg = colors.bright_green },
  ['@variable.parameter'] = { fg = colors.fg },
  ['@markup.heading'] = { fg = colors.fg_bright, bold = true },
  ['@markup.bold'] = { bold = true, fg = colors.fg_bright },
  ['@markup.italic'] = { italic = true },
  ['@markup.underline'] = { underline = true },
  ['@markup.link'] = { fg = colors.cyan, underline = true },
  ['@markup.quote'] = { fg = colors.bright_green, italic = true },
  ['@markup.raw'] = { fg = colors.bright_yellow },
})

for group, opts in pairs(groups) do
  vim.api.nvim_set_hl(0, group, opts)
end
