#!/usr/bin/bash

s="$(nvidia-settings -q CurrentMetaMode -t)"

if [[ "$s" != "" ]]; then
    s="${s#*" :: "}"
    nvidia-settings -a CurrentMetaMode="${s//\}/, ForceCompositionPipeline=On\}}"
fi

sleep 3

declare -a wallpapers=(
     "pexels-didsss-9656151.jpg"
     "pexels-nadezhda-moryak-6063609.jpg"
     "pexels-codioful-6985184.jpg"
)

count="$(xrandr | grep "*" | wc -l)"
echo $count

for (( i=0; i<=$count; i++))
do
    echo "$HOME/.wallpapers/${wallpapers[$i]}"
    nitrogen --head=$((i-1)) --set-zoom-fill "$HOME/.wallpapers/${wallpapers[$i]}"
done
