#!/usr/bin/bash

s="$(nvidia-settings -q CurrentMetaMode -t)"

if [[ "$s" != "" ]]; then
    s="${s#*" :: "}"
    nvidia-settings -a CurrentMetaMode="${s//\}/, ForceCompositionPipeline=On\}}"
fi

sleep 3

declare -a wallpapers=(
    "pexels-kanhaiya-sharma-284427440-13062567.jpg"
    "pexels-steve-29008328.jpg"
    "pexels-marek-piwnicki-3907296-30052780.jpg"
)

count="$(xrandr | grep "*" | wc -l)"
echo $count

for (( i=0; i<=$count; i++))
do
    echo "$HOME/.wallpapers/${wallpapers[$i]}"
    nitrogen --head=$((i-1)) --set-zoom-fill "$HOME/.wallpapers/${wallpapers[$i]}"
done
